export type Category = {
  id: string;
  name: string;
  kind: "despesa" | "entrada";
  icon: string;
  color: string;
  isGlobal: boolean;
  userId?: string | null;
};

export type Transaction = {
  id: string;
  type: "entrada" | "despesa";
  date: string; // YYYY-MM-DD
  description: string;
  categoryId?: string;
  amount: number;
  essential: boolean;
  fixed: boolean;
  // Fase 1.1 — log de geração automática
  autoGenerated?: boolean;
  recurringId?: string | null;
};

export type Filters = {
  period: "7d" | "30d" | "all";
  categoryId: string; // "all" or id
  search: string;
  type: "all" | "entrada" | "despesa";
};

export type Budget = {
  id: string;
  categoryId: string;
  amount: number;
  period: "monthly" | "weekly";
};

export type Goal = {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  targetDate?: string | null;
  icon: string;
  color: string;
  completed: boolean;
};

export type RecurringFrequency = "daily" | "weekly" | "monthly" | "yearly";

export type Recurring = {
  id: string;
  type: "entrada" | "despesa";
  description: string;
  amount: number;
  categoryId?: string | null;
  frequency: RecurringFrequency;
  startDate: string;
  endDate?: string | null;
  nextRun: string;
  essential: boolean;
  fixed: boolean;
  active: boolean;
  // Fase 1.1 — pausar/retomar e pular ocorrências
  pausedUntil?: string | null;
  skipDates?: string[];
};

export type AppState = {
  transactions: Transaction[];
  preferences: {
    persistLocal: boolean;
    clearOnLogout: boolean;
  };
  session: {
    loggedOut: boolean;
  };
};
