/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppRegistrosRouteImport } from './routes/_app.registros'
import { Route as AppRecorrentesRouteImport } from './routes/_app.recorrentes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppOrcamentosRouteImport } from './routes/_app.orcamentos'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppInteligenciaRouteImport } from './routes/_app.inteligencia'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrosRoute = AppRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AppRoute,
} as any)
const AppRecorrentesRoute = AppRecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AppCategoriasRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/metas': typeof AppMetasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/recorrentes': typeof AppRecorrentesRoute
  '/registros': typeof AppRegistrosRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AppCategoriasRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/metas': typeof AppMetasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/recorrentes': typeof AppRecorrentesRoute
  '/registros': typeof AppRegistrosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/inteligencia': typeof AppInteligenciaRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/recorrentes': typeof AppRecorrentesRoute
  '/_app/registros': typeof AppRegistrosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/inteligencia'
    | '/metas'
    | '/orcamentos'
    | '/perfil'
    | '/recorrentes'
    | '/registros'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/inteligencia'
    | '/metas'
    | '/orcamentos'
    | '/perfil'
    | '/recorrentes'
    | '/registros'
    | '/relatorios'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/categorias'
    | '/_app/inteligencia'
    | '/_app/metas'
    | '/_app/orcamentos'
    | '/_app/perfil'
    | '/_app/recorrentes'
    | '/_app/registros'
    | '/_app/relatorios'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registros': {
      id: '/_app/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AppRegistrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recorrentes': {
      id: '/_app/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof AppRecorrentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inteligencia': {
      id: '/_app/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppMetasRoute: typeof AppMetasRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRecorrentesRoute: typeof AppRecorrentesRoute
  AppRegistrosRoute: typeof AppRegistrosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppMetasRoute: AppMetasRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRecorrentesRoute: AppRecorrentesRoute,
  AppRegistrosRoute: AppRegistrosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
